### ISSUE TITLE
idea: give a location string (address) to LocationPickerActivity

### ISSUE THREAD

**Issue by Rainer-Lang** [Livinlawrence/LocationPicker#2]

**Comment by Livinlawrence** [comment]
I will be adding a extra string parameter for location(Address), is that you suggested..?

**Comment by Rainer-Lang** [comment]
Now I can use geo-coordinates - but I also want to use an address like:
"Meerstr. 15, 87264 Hamburg, Germany"

I think you understood me :-)
Thanks.

**Comment by Rainer-Lang** [comment]
Please make it possible that I can pass more than one location.
An array would be fine - for addresses and/or geo-coords.
